### PR TITLE
use openapi v3.0.3 and update swagger-ui

### PR DESCRIPTION
**Pull request by ax-mnakama**
This is to support OpenAPI 3. From my own testing, this appears to be all that's needed, but I might be missing something.

https://github.com/mrk-andreev/tornado-swagger/issues/15

### CODE REVIEW

**Comment by zivmc** [comment]
It seems that the model definitions do not work well.

I run examples/model_declaration.py under this branch and found models not displayed on the web page.

**Comment by zivmc** [comment]
I modified "definitions" in swagger_spec into the following:

```
        "components": {
            "schemas": export_swagger_models(),
        },
```

and modified `$ref: '#/definitions/PostModel'` into `$ref: '#/components/schemas/PostModel'`, then the models work fine.

While such kind of modifications are not backward compatible, I guess this pull request should not be merged into master branch.

**Comment by ax-mnakama** [comment]
Thanks for looking this over. To my understanding, openapi 3.0 is not backwards compatible with swagger 2.0, but I assumed that we should be migrating things... maybe a new openapi-3 branch?

**Comment by mrk-andreev** [comment]
Now openapi3 available as experimental feature. You can complete openapi3 support if it is required - https://github.com/mrk-andreev/tornado-swagger/blob/master/tornado_swagger/_builders.py#L203

**Pull request closed without merging**
