### PR TITLE
Add github action test workflow

### PR DESCRIPTION
**Pull request by luiscoms**
I've comment the `flake8-erradicate` and downgrade `flake8-isort` that was causing conflicts

```
$ pip install requirementes-dev.txt
.....
The conflict is caused by:
    The user requested flake8==5.0.4
    flake8-annotations-complexity 0.0.7 depends on flake8
    flake8-bugbear 22.7.1 depends on flake8>=3.0.0
    flake8-builtins 1.5.3 depends on flake8
    flake8-comprehensions 3.10.0 depends on flake8!=3.2.0 and >=3.0
    flake8-eradicate 1.2.1 depends on flake8<5 and >=3.5
```

### CODE REVIEW

**Comment by mrk-andreev** [comment]
Thanks for your activity.

- In https://github.com/mrk-andreev/tornado-swagger/pull/66 I fixed this issue (release 1.4.5). 
- Now I can test application across python version https://github.com/mrk-andreev/tornado-swagger/blob/master/run_tests_in_docker.bash

**Comment by luiscoms** [comment]
The objective here is to test on windows

**Comment by mrk-andreev** [comment]
Thank you for you example. I will add your github workflow as soon as possible:)

Thank you for your help ☺️

**Comment by mrk-andreev** [comment]
@luiscoms , thank a lot!

Now you change in mainstream (https://github.com/mrk-andreev/tornado-swagger/pull/67) - https://github.com/mrk-andreev/tornado-swagger/blob/master/.github/workflows/test.yml

**Comment by luiscoms** [comment]
You are welcome, now issue #56 was fixed \o/

**Pull request closed without merging**
